### ISSUE TITLE
Set up major mode of AtomicChrome buffer?

### ISSUE THREAD

**Issue by joostkremers** [alpha22jp/atomic-chrome#1]
Hi, I just noticed your package on Melpa and since I've never been entirely happy with `edit-with-emacs`, I thought I'd give it a try. Looks good so far, the live update is great! (I'm using it with Chromium, BTW, seems to work just fine.)

I do have one question, though: is there a way to specify the major mode of the edit buffer that is being created? Manually changing the major mode apparently disrupts the connection back to Chromium, because updates in the Emacs buffer are no longer propagated back.

I'm aware of `atomic-chrome-edit-mode-hook`, but that's a minor mode hook, so not really the place to change the major mode. (And it might suffer from the same problem of the connection being disrupted, I don't know, haven't tested.)

Ok, looking at the code, I see that there probably isn't a way to set the major mode. In that case, I would like to make this a feature request. :-) Ideally, there'd be something like `edit-server-default-major-mode` and `edit-server-url-major-mode-alist`, because it's nice to be able to edit text boxes on Github with `gfm-mode`.

**Comment by alpha22jp** [comment]
Hi @joostkremers,

Thanks for your feedback. As you write, `atomic-chrome-edit-mode-hook` doesn't help set major mode for editing buffer. Because the buffer local variable `atomic-chrome-buffer-ws` which keeps the websocket connection information is lost when major mode is changed. So I commited 6fe75d4 to add a customizable variable `atomic-chrome-default-major-mode` just like `edit-mode-default-major-mode`.

As for `edit-server-url-major-mode-alist` issue, it's easy to add the similar variable but there is one problem. Atomic chrome extension doesn't send page URL. It sends page title instead. I think page title is useless to switch major mode.

**Comment by joostkremers** [comment]
>  So I commited 6fe75d4 to add a customizable variable `atomic-chrome-default-major-mode` just like `edit-mode-default-major-mode`.

Great, thanks! I'm typing this in `markdown-mode` right now.

> Atomic chrome extension doesn't send page URL. It sends page title instead. I think page title is useless to switch major mode.

Ah, I see. I agree that the page title is useless for choosing the major mode. Anyway, it's not a big problem.

I'll close this issue now as my problem has been solved.

**Comment by mankoff** [comment]
Fixed! See #3
