### ISSUE TITLE
C-c C-c with no edits prompts about unsaved changes

### ISSUE THREAD

**Issue by raxod502** [alpha22jp/atomic-chrome#42]
The issue can be reproduced from `emacs -Q`:

1. Load `atomic-chrome`, revision e96e3a055bec9cc74c48b8e67fd43f784b8079fb.
2. Run `M-x atomic-chrome-start-server`.
3. In Chrome, edit a text area to contain some text.
4. Trigger the extension and switch to Emacs.
5. Press `C-c C-c` in the new buffer.
6. Receive the unexpected prompt `Buffer has not been saved, close anyway?` in minibuffer.

Expected behavior would be to not receive any prompt here, I think. With the default configuration of `atomic-chrome-enable-auto-update` as non-nil, performing any command in the buffer before pressing `C-c C-c` will eliminate the problematic behavior.

See also https://github.com/alpha22jp/atomic-chrome/issues/37.

I tried to figure out why this happens, but got confused, so I'm leaving this here for now.

**Comment by stevevdvkpe** [comment]
Does this help?  It clears buffer-modified-p the first time a buffer is created and the text from the textarea is first inserted.
```
--- atomic-chrome.el~	2018-03-21 14:50:29.200615891 -0700
+++ atomic-chrome.el	2018-07-05 11:42:36.852943451 -0700
@@ -201,7 +201,8 @@
              (list socket (atomic-chrome-show-edit-buffer buffer title))
              atomic-chrome-buffer-table)
       (atomic-chrome-set-major-mode url)
-      (insert text))))
+      (insert text)
+      (set-buffer-modified-p nil))))
 
 (defun atomic-chrome-close-edit-buffer (buffer)
   "Close buffer BUFFER if it's one of Atomic Chrome edit buffers."

**Comment by raxod502** [comment]
No, wait—that doesn't fix it entirely. The first time I press `C-c C-c`, it still prompts. But each subsequent time I use `C-c C-c` on a buffer which came from the same webpage, it doesn't prompt anymore, which confused my testing.

The part where the behavior changes after I use `C-c C-c` appears to persist across Emacs sessions, somehow. Maybe the Chrome extension is sending a different message on the socket for the first edit, and this message doesn't trigger the code path you modified.

**Comment by stevevdvkpe** [comment]
Radon Rosborough writes:
 > No, wait—that doesn't fix it entirely. The first time I press C-c C-c, it
 > still prompts. But each subsequent time I use C-c C-c on a buffer which came
 > from the same webpage, it doesn't prompt anymore, which confused my testing.

Does it not prompt even when the buffer is modified?

 > The part where the behavior changes after I use C-c C-c appears to persist
 > across Emacs sessions, somehow. Maybe the Chrome extension is sending a
 > different message on the socket for the first edit, and this message doesn't
 > trigger the code path you modified.

I kind of wonder if it's using the same buffer when you edit the same
textarea again, which would explain what you're seeing; I tried clearing
buffer-modified-p in the function that first creates a buffer and
inserts the text from the textarea.  If the buffer is reused then a
different function is called to update the buffer from the textarea.
However, in that case it's also not that easy to distinguish from
buffer updates that would occur when the textarea is edited in the
browser, which also sends a buffer update message to Emacs.

I am not that expert in the internals of atomic-chrome myself so I may
have to do some more research and experimentation.

**Comment by raxod502** [comment]
> Does it not prompt even when the buffer is modified?

It does prompt when the buffer is modified. That's not the issue—the problem is that it _does_ prompt the first time, even if the buffer is not modified.

> I kind of wonder if it's using the same buffer when you edit the same textarea again

That can't be it; how could the same buffer persist after Emacs is killed and restarted?

**Comment by stevevdvkpe** [comment]
Radon Rosborough writes:
 > No, wait—that doesn't fix it entirely. The first time I press C-c C-c, it
 > still prompts. But each subsequent time I use C-c C-c on a buffer which came
 > from the same webpage, it doesn't prompt anymore, which confused my testing.
 > 
 > The part where the behavior changes after I use C-c C-c appears to persist
 > across Emacs sessions, somehow. Maybe the Chrome extension is sending a
 > different message on the socket for the first edit, and this message doesn't
 > trigger the code path you modified.

I'm afraid my own testing has gotten really confusing too.  The first
time I try to edit a textarea, it does seem to work in the way I'm
expecting: Emacs opens a frame with the textarea contents, and
buffer-modified-p is initially nil so C-c C-c just closes the frame
without prompting.  If I then try to re-edit the same text area it looks
like atomic-chrome creates *two* sessions, one of which may or may not
start with buffer-modified-p set to nil.  And if I close both of those
and try a third time, I get *three* sessions opened in sequence, and so
on.

My sense is that something about the way atomic-chrome interacts with
Emacs is wonky and one or the other isn't properly closing down sessions
started from the same web page and textarea through multiple attempts to
edit the same textarea with Ghost Text.  But that's definitely beyond my
ability to debug since I don't really know anything about websockets.

**Comment by raxod502** [comment]
It's not too annoying of a bug once I apply your partial fix, so I'll leave it be for now. Mayhaps I will come back to it, though.

**Comment by stevevdvkpe** [comment]
Out of curiosity, which browser are you using?  I'm getting my funny behavior (multiple editing frames on re-editing the same textarea) with Ghost Text in Firefox interacting with atomic-chrome.el in Emacs 24.5.  So I'm wondering if the bug is in the browser extension or in atomic-chrome.el.  I can even see multiple websocket sessions open between Firefox and Emacs after using C-c C-c to close the Emacs editing frame.

Based on what I can suss out from how atomic-chrome.el appears to interact with the websocket from the browser, the fix I proposed *should* work but the multiple websocket sessions might well be what is producing some of the confusing Emacs behavior.

**Comment by raxod502** [comment]
I'm using Google Chrome. Apart from that I don't know much, though—I haven't dug into this code nearly as much as you.

I can definitely believe that the websocket/JSON messaging behavior is different between the two extensions, though!

**Comment by titanofold** [comment]
As of today, `C-c C-c` works for me.

 (Emacs 26.1, Windows 7 Pro, Firefox 66.0.2, Atomic Chrome 20180617.724)

**Comment by raxod502** [comment]
When I tested just now, the behavior I described in https://github.com/alpha22jp/atomic-chrome/issues/42#issuecomment-403071672 appears to no longer exist. Hence, I am closing this issue—it appears to be resolved.
